import type { Episode, EpisodesGroupedBySeason, GroupedShowsByGenre, Show } from "@/types";

export const unsortedShows: Show[] = [
  // Music - 3 items
  {
    id: 288,
    url: "https://www.tvmaze.com/shows/288/american-idol",
    name: "American Idol",
    type: "Reality",
    language: "English",
    genres: ["Music"],
    status: "Running",
    runtime: 120,
    averageRuntime: 118,
    premiered: "2002-06-11",
    ended: null,
    officialSite: "https://abc.com/shows/american-idol/",
    schedule: { time: "20:00", days: ["Monday", "Sunday"] },
    rating: { average: 5.1 },
    weight: 98,
    network: {
      id: 3,
      name: "ABC",
      country: { name: "United States", code: "US", timezone: "America/New_York" },
      officialSite: "https://abc.com/",
    },
    webChannel: null,
    dvdCountry: null,
    externals: { tvrage: 2601, thetvdb: 70814, imdb: "tt0319931" },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_portrait/507/1267848.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/507/1267848.jpg",
    },
    summary:
      "<p><b>American Idol </b>is an American singing competition show, where contestants perform in front of a panel of star judges, representing the music industry. The winner is determined by viewers' vote.</p>",
    updated: 1709667891,
    _links: {
      self: { href: "https://api.tvmaze.com/shows/288" },
      previousepisode: { href: "https://api.tvmaze.com/episodes/2782179" },
      nextepisode: { href: "https://api.tvmaze.com/episodes/2782180" },
    },
  },
  {
    id: 289,
    url: "https://www.tvmaze.com/shows/289/americas-got-talent",
    name: "America's Got Talent",
    type: "Variety",
    language: "English",
    genres: ["Music"],
    status: "Running",
    runtime: 120,
    averageRuntime: 112,
    premiered: "2006-06-21",
    ended: null,
    officialSite: "http://www.nbc.com/americas-got-talent",
    schedule: { time: "20:00", days: ["Tuesday"] },
    rating: { average: 5.8 },
    weight: 90,
    network: {
      id: 1,
      name: "NBC",
      country: { name: "United States", code: "US", timezone: "America/New_York" },
      officialSite: "https://www.nbc.com/",
    },
    webChannel: null,
    dvdCountry: null,
    externals: { tvrage: 10408, thetvdb: 79490, imdb: "tt0759364" },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_portrait/462/1156593.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/462/1156593.jpg",
    },
    summary:
      "<p>With the talent search open to acts of all ages, <b>America's Got Talent</b> has brought the variety format back to the forefront of American culture by showcasing performers from across the country. The series is a true celebration of the American spirit, featuring a colorful array of singers, dancers, comedians, contortionists, impressionists, jugglers, magicians, ventriloquists and hopeful stars, all vying for their chance to win America's hearts and the $1 million prize.</p>",
    updated: 1706780642,
    _links: {
      self: { href: "https://api.tvmaze.com/shows/289" },
      previousepisode: { href: "https://api.tvmaze.com/episodes/2599860" },
    },
  },
  {
    id: 361,
    url: "https://www.tvmaze.com/shows/361/saturday-night-live",
    name: "Saturday Night Live",
    type: "Variety",
    language: "English",
    genres: ["Comedy", "Music"],
    status: "Running",
    runtime: 90,
    averageRuntime: 90,
    premiered: "1975-10-11",
    ended: null,
    officialSite: "http://www.nbc.com/saturday-night-live",
    schedule: { time: "23:29", days: ["Saturday"] },
    rating: { average: 5.9 },
    weight: 99,
    network: {
      id: 1,
      name: "NBC",
      country: { name: "United States", code: "US", timezone: "America/New_York" },
      officialSite: "https://www.nbc.com/",
    },
    webChannel: null,
    dvdCountry: null,
    externals: { tvrage: 5098, thetvdb: 76177, imdb: "tt0072562" },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_portrait/446/1115535.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/446/1115535.jpg",
    },
    summary:
      '<p><b>Saturday Night Live</b> is an Emmy Award-winning late-night comedy showcase.</p><p>Since its inception in 1975, "SNL" has launched the careers of many of the brightest comedy performers of their generation. As The New York Times noted on the occasion of the show\'s Emmy-winning 25th Anniversary special in 1999, "in defiance of both time and show business convention, \'SNL\' is still the most pervasive influence on the art of comedy in contemporary culture." At the close of the century, "Saturday Night Live" placed seventh on Entertainment Weekly\'s list of the Top 100 Entertainers of the past fifty years.</p>',
    updated: 1710360492,
    _links: {
      self: { href: "https://api.tvmaze.com/shows/361" },
      previousepisode: { href: "https://api.tvmaze.com/episodes/2775836" },
      nextepisode: { href: "https://api.tvmaze.com/episodes/2788997" },
    },
  },
  // Animation - 2 items
  {
    id: 488,
    url: "https://www.tvmaze.com/shows/488/naruto-shippuden",
    name: "Naruto: Shippūden",
    type: "Animation",
    language: "Japanese",
    genres: ["Action", "Adventure", "Anime", "Fantasy"],
    status: "Ended",
    runtime: 30,
    averageRuntime: 30,
    premiered: "2007-02-15",
    ended: "2017-03-23",
    officialSite: "http://www.tv-tokyo.co.jp/anime/naruto/index2.html",
    schedule: { time: "19:30", days: ["Thursday"] },
    rating: { average: 8.6 },
    weight: 97,
    network: {
      id: 76,
      name: "TV Tokyo",
      country: { name: "Japan", code: "JP", timezone: "Asia/Tokyo" },
      officialSite: null,
    },
    webChannel: {
      id: 20,
      name: "Crunchyroll",
      country: null,
      officialSite: "https://www.crunchyroll.com/",
    },
    dvdCountry: null,
    externals: { tvrage: 14748, thetvdb: 79824, imdb: "tt0988824" },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_portrait/3/9413.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/3/9413.jpg",
    },
    summary:
      "<p><b>Naruto: Shippuden</b> is the continuation of the original animated TV series Naruto.The story revolves around an older and slightly more matured Uzumaki Naruto and his quest to save his friend Uchiha Sasuke from the grips of the snake-like Shinobi, Orochimaru. After 2 and a half years Naruto finally returns to his village of Konoha, and sets about putting his ambitions to work, though it will not be easy, as he has amassed a few (more dangerous) enemies, in the likes of the shinobi organization; Akatsuki.</p>",
    updated: 1710479806,
    _links: {
      self: { href: "https://api.tvmaze.com/shows/488" },
      previousepisode: { href: "https://api.tvmaze.com/episodes/1099850" },
    },
  },
  {
    id: 495,
    url: "https://www.tvmaze.com/shows/495/naruto",
    name: "Naruto",
    type: "Animation",
    language: "Japanese",
    genres: ["Action", "Adventure", "Anime", "Fantasy"],
    status: "Ended",
    runtime: 30,
    averageRuntime: 30,
    premiered: "2002-10-03",
    ended: "2007-02-08",
    officialSite: "http://www.tv-tokyo.co.jp/anime/naruto/index2.html",
    schedule: { time: "19:30", days: ["Thursday"] },
    rating: { average: 8.3 },
    weight: 93,
    network: {
      id: 76,
      name: "TV Tokyo",
      country: { name: "Japan", code: "JP", timezone: "Asia/Tokyo" },
      officialSite: null,
    },
    webChannel: {
      id: 20,
      name: "Crunchyroll",
      country: null,
      officialSite: "https://www.crunchyroll.com/",
    },
    dvdCountry: null,
    externals: { tvrage: 4620, thetvdb: 78857, imdb: "tt0409591" },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_portrait/3/9744.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/3/9744.jpg",
    },
    summary:
      "<p><b>Naruto</b> closely follows the life of a boy who is feared and detested by the villagers of the hidden leaf village of Konoha. The distrust of the boy has little to do with the boy himself, but it's what's inside him that causes anxiety. Long before Naruto came to be, a Kyuubi (demon fox) with great fury and power waged war taking many lives. The battle ensued for a long time until a man known as the Fourth Hokage, Yondaime, the strongest ninja in Konoha, fiercely fought the Kyuubi. The fight was soon won by Yondaime as he sealed the evil demon in a human body. Thus the boy, Naruto, was born. As Naruto grows he decides to become the strongest ninja in Konoha in an effort to show everyone that he is not as they perceive him to be, but is a human being worthy of love and admiration. But the road to becoming Hokage, the title for the strongest ninja in Konoha, is a long and arduous one. It is a path filled with betrayal, pain, and loss; but with hard work, Naruto may achieve Hokage.</p>",
    updated: 1704793874,
    _links: {
      self: { href: "https://api.tvmaze.com/shows/495" },
      previousepisode: { href: "https://api.tvmaze.com/episodes/45225" },
    },
  },
  // Legal - 1 item
  {
    id: 280,
    url: "https://www.tvmaze.com/shows/280/franklin-bash",
    name: "Franklin & Bash",
    type: "Scripted",
    language: "English",
    genres: ["Drama", "Comedy", "Legal"],
    status: "Ended",
    runtime: 60,
    averageRuntime: 60,
    premiered: "2011-06-01",
    ended: "2014-10-22",
    officialSite: null,
    schedule: { time: "22:00", days: ["Wednesday"] },
    rating: { average: 7 },
    weight: 49,
    network: {
      id: 14,
      name: "TNT",
      country: { name: "United States", code: "US", timezone: "America/New_York" },
      officialSite: "https://www.tntdrama.com/",
    },
    webChannel: null,
    dvdCountry: null,
    externals: { tvrage: 25844, thetvdb: 164041, imdb: "tt1600199" },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_portrait/1/4800.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/1/4800.jpg",
    },
    summary:
      "<p>Two young, fly-by-the-seat-of-their-pants street lawyers cause a seismic culture clash when they join a legendary, button-down law firm.</p>",
    updated: 1704793509,
    _links: {
      self: { href: "https://api.tvmaze.com/shows/280" },
      previousepisode: { href: "https://api.tvmaze.com/episodes/28973" },
    },
  },
];

export const sortedShows: Show[] = [
  {
    id: 488,
    url: "https://www.tvmaze.com/shows/488/naruto-shippuden",
    name: "Naruto: Shippūden",
    type: "Animation",
    language: "Japanese",
    genres: ["Action", "Adventure", "Anime", "Fantasy"],
    status: "Ended",
    runtime: 30,
    averageRuntime: 30,
    premiered: "2007-02-15",
    ended: "2017-03-23",
    officialSite: "http://www.tv-tokyo.co.jp/anime/naruto/index2.html",
    schedule: {
      time: "19:30",
      days: ["Thursday"],
    },
    rating: {
      average: 8.6,
    },
    weight: 97,
    network: {
      id: 76,
      name: "TV Tokyo",
      country: {
        name: "Japan",
        code: "JP",
        timezone: "Asia/Tokyo",
      },
      officialSite: null,
    },
    webChannel: {
      id: 20,
      name: "Crunchyroll",
      country: null,
      officialSite: "https://www.crunchyroll.com/",
    },
    dvdCountry: null,
    externals: {
      tvrage: 14748,
      thetvdb: 79824,
      imdb: "tt0988824",
    },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_portrait/3/9413.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/3/9413.jpg",
    },
    summary:
      "<p><b>Naruto: Shippuden</b> is the continuation of the original animated TV series Naruto.The story revolves around an older and slightly more matured Uzumaki Naruto and his quest to save his friend Uchiha Sasuke from the grips of the snake-like Shinobi, Orochimaru. After 2 and a half years Naruto finally returns to his village of Konoha, and sets about putting his ambitions to work, though it will not be easy, as he has amassed a few (more dangerous) enemies, in the likes of the shinobi organization; Akatsuki.</p>",
    updated: 1710479806,
    _links: {
      self: {
        href: "https://api.tvmaze.com/shows/488",
      },
      previousepisode: {
        href: "https://api.tvmaze.com/episodes/1099850",
      },
    },
  },
  {
    id: 495,
    url: "https://www.tvmaze.com/shows/495/naruto",
    name: "Naruto",
    type: "Animation",
    language: "Japanese",
    genres: ["Action", "Adventure", "Anime", "Fantasy"],
    status: "Ended",
    runtime: 30,
    averageRuntime: 30,
    premiered: "2002-10-03",
    ended: "2007-02-08",
    officialSite: "http://www.tv-tokyo.co.jp/anime/naruto/index2.html",
    schedule: {
      time: "19:30",
      days: ["Thursday"],
    },
    rating: {
      average: 8.3,
    },
    weight: 93,
    network: {
      id: 76,
      name: "TV Tokyo",
      country: {
        name: "Japan",
        code: "JP",
        timezone: "Asia/Tokyo",
      },
      officialSite: null,
    },
    webChannel: {
      id: 20,
      name: "Crunchyroll",
      country: null,
      officialSite: "https://www.crunchyroll.com/",
    },
    dvdCountry: null,
    externals: {
      tvrage: 4620,
      thetvdb: 78857,
      imdb: "tt0409591",
    },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_portrait/3/9744.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/3/9744.jpg",
    },
    summary:
      "<p><b>Naruto</b> closely follows the life of a boy who is feared and detested by the villagers of the hidden leaf village of Konoha. The distrust of the boy has little to do with the boy himself, but it's what's inside him that causes anxiety. Long before Naruto came to be, a Kyuubi (demon fox) with great fury and power waged war taking many lives. The battle ensued for a long time until a man known as the Fourth Hokage, Yondaime, the strongest ninja in Konoha, fiercely fought the Kyuubi. The fight was soon won by Yondaime as he sealed the evil demon in a human body. Thus the boy, Naruto, was born. As Naruto grows he decides to become the strongest ninja in Konoha in an effort to show everyone that he is not as they perceive him to be, but is a human being worthy of love and admiration. But the road to becoming Hokage, the title for the strongest ninja in Konoha, is a long and arduous one. It is a path filled with betrayal, pain, and loss; but with hard work, Naruto may achieve Hokage.</p>",
    updated: 1704793874,
    _links: {
      self: {
        href: "https://api.tvmaze.com/shows/495",
      },
      previousepisode: {
        href: "https://api.tvmaze.com/episodes/45225",
      },
    },
  },
  {
    id: 280,
    url: "https://www.tvmaze.com/shows/280/franklin-bash",
    name: "Franklin & Bash",
    type: "Scripted",
    language: "English",
    genres: ["Drama", "Comedy", "Legal"],
    status: "Ended",
    runtime: 60,
    averageRuntime: 60,
    premiered: "2011-06-01",
    ended: "2014-10-22",
    officialSite: null,
    schedule: {
      time: "22:00",
      days: ["Wednesday"],
    },
    rating: {
      average: 7,
    },
    weight: 49,
    network: {
      id: 14,
      name: "TNT",
      country: {
        name: "United States",
        code: "US",
        timezone: "America/New_York",
      },
      officialSite: "https://www.tntdrama.com/",
    },
    webChannel: null,
    dvdCountry: null,
    externals: {
      tvrage: 25844,
      thetvdb: 164041,
      imdb: "tt1600199",
    },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_portrait/1/4800.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/1/4800.jpg",
    },
    summary:
      "<p>Two young, fly-by-the-seat-of-their-pants street lawyers cause a seismic culture clash when they join a legendary, button-down law firm.</p>",
    updated: 1704793509,
    _links: {
      self: {
        href: "https://api.tvmaze.com/shows/280",
      },
      previousepisode: {
        href: "https://api.tvmaze.com/episodes/28973",
      },
    },
  },
  {
    id: 361,
    url: "https://www.tvmaze.com/shows/361/saturday-night-live",
    name: "Saturday Night Live",
    type: "Variety",
    language: "English",
    genres: ["Comedy", "Music"],
    status: "Running",
    runtime: 90,
    averageRuntime: 90,
    premiered: "1975-10-11",
    ended: null,
    officialSite: "http://www.nbc.com/saturday-night-live",
    schedule: {
      time: "23:29",
      days: ["Saturday"],
    },
    rating: {
      average: 5.9,
    },
    weight: 99,
    network: {
      id: 1,
      name: "NBC",
      country: {
        name: "United States",
        code: "US",
        timezone: "America/New_York",
      },
      officialSite: "https://www.nbc.com/",
    },
    webChannel: null,
    dvdCountry: null,
    externals: {
      tvrage: 5098,
      thetvdb: 76177,
      imdb: "tt0072562",
    },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_portrait/446/1115535.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/446/1115535.jpg",
    },
    summary:
      '<p><b>Saturday Night Live</b> is an Emmy Award-winning late-night comedy showcase.</p><p>Since its inception in 1975, "SNL" has launched the careers of many of the brightest comedy performers of their generation. As The New York Times noted on the occasion of the show\'s Emmy-winning 25th Anniversary special in 1999, "in defiance of both time and show business convention, \'SNL\' is still the most pervasive influence on the art of comedy in contemporary culture." At the close of the century, "Saturday Night Live" placed seventh on Entertainment Weekly\'s list of the Top 100 Entertainers of the past fifty years.</p>',
    updated: 1710360492,
    _links: {
      self: {
        href: "https://api.tvmaze.com/shows/361",
      },
      previousepisode: {
        href: "https://api.tvmaze.com/episodes/2775836",
      },
      nextepisode: {
        href: "https://api.tvmaze.com/episodes/2788997",
      },
    },
  },
  {
    id: 289,
    url: "https://www.tvmaze.com/shows/289/americas-got-talent",
    name: "America's Got Talent",
    type: "Variety",
    language: "English",
    genres: ["Music"],
    status: "Running",
    runtime: 120,
    averageRuntime: 112,
    premiered: "2006-06-21",
    ended: null,
    officialSite: "http://www.nbc.com/americas-got-talent",
    schedule: {
      time: "20:00",
      days: ["Tuesday"],
    },
    rating: {
      average: 5.8,
    },
    weight: 90,
    network: {
      id: 1,
      name: "NBC",
      country: {
        name: "United States",
        code: "US",
        timezone: "America/New_York",
      },
      officialSite: "https://www.nbc.com/",
    },
    webChannel: null,
    dvdCountry: null,
    externals: {
      tvrage: 10408,
      thetvdb: 79490,
      imdb: "tt0759364",
    },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_portrait/462/1156593.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/462/1156593.jpg",
    },
    summary:
      "<p>With the talent search open to acts of all ages, <b>America's Got Talent</b> has brought the variety format back to the forefront of American culture by showcasing performers from across the country. The series is a true celebration of the American spirit, featuring a colorful array of singers, dancers, comedians, contortionists, impressionists, jugglers, magicians, ventriloquists and hopeful stars, all vying for their chance to win America's hearts and the $1 million prize.</p>",
    updated: 1706780642,
    _links: {
      self: {
        href: "https://api.tvmaze.com/shows/289",
      },
      previousepisode: {
        href: "https://api.tvmaze.com/episodes/2599860",
      },
    },
  },
  {
    id: 288,
    url: "https://www.tvmaze.com/shows/288/american-idol",
    name: "American Idol",
    type: "Reality",
    language: "English",
    genres: ["Music"],
    status: "Running",
    runtime: 120,
    averageRuntime: 118,
    premiered: "2002-06-11",
    ended: null,
    officialSite: "https://abc.com/shows/american-idol/",
    schedule: {
      time: "20:00",
      days: ["Monday", "Sunday"],
    },
    rating: {
      average: 5.1,
    },
    weight: 98,
    network: {
      id: 3,
      name: "ABC",
      country: {
        name: "United States",
        code: "US",
        timezone: "America/New_York",
      },
      officialSite: "https://abc.com/",
    },
    webChannel: null,
    dvdCountry: null,
    externals: {
      tvrage: 2601,
      thetvdb: 70814,
      imdb: "tt0319931",
    },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_portrait/507/1267848.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/507/1267848.jpg",
    },
    summary:
      "<p><b>American Idol </b>is an American singing competition show, where contestants perform in front of a panel of star judges, representing the music industry. The winner is determined by viewers' vote.</p>",
    updated: 1709667891,
    _links: {
      self: {
        href: "https://api.tvmaze.com/shows/288",
      },
      previousepisode: {
        href: "https://api.tvmaze.com/episodes/2782179",
      },
      nextepisode: {
        href: "https://api.tvmaze.com/episodes/2782180",
      },
    },
  },
];

export const episodes: Episode[] = [
  {
    id: 40286,
    url: "https://www.tvmaze.com/episodes/40286/farscape-1x01-premiere",
    name: "Premiere",
    season: 1,
    number: 1,
    type: "regular",
    airdate: "1999-03-19",
    airtime: "20:00",
    airstamp: "1999-03-20T01:00:00+00:00",
    runtime: 60,
    rating: { average: 6.7 },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_landscape/199/499198.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/199/499198.jpg",
    },
    summary:
      "<p>Astronaut John Crichton attempts to use the Earth's atmosphere to propel his module <i>Farscape 1</i> at high speeds but he is hit by a radiation wave and sucked through a wormhole into a distant part of the universe and straight into the middle of a space battle. After almost colliding with another ship, which explodes shortly afterwards, he is brought aboard a ship full of alien prisoners attempting to escape custody. After being partnered with a captured Peacekeeper soldier, Crichton is drawn into the prisoners' daring plan to escape the clutches of the Peacekeeper forces and their vengefully obsessed military commander.</p>",
    _links: {
      self: { href: "https://api.tvmaze.com/episodes/40286" },
      show: { href: "https://api.tvmaze.com/shows/429" },
    },
  },
  {
    id: 40290,
    url: "https://www.tvmaze.com/episodes/40290/farscape-1x02-back-and-back-and-back-to-the-future",
    name: "Back and Back and Back to the Future",
    season: 1,
    number: 2,
    type: "regular",
    airdate: "1999-03-26",
    airtime: "20:00",
    airstamp: "1999-03-27T01:00:00+00:00",
    runtime: 60,
    rating: { average: 7.2 },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_landscape/448/1121513.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/448/1121513.jpg",
    },
    summary:
      "<p>The crew comes across a ship that is molecularly de-stabilizing. D'Argo makes everyone bring the ship's escape pod aboard when he discovers that the ship's passengers are Ilanics -- long-time allies of the Luxans. Aboard the escape pod, Crichton gets a shock and starts experiencing strange visions of the future, first of himself and one of the Ilanics, then of <i>Moya's</i> destruction.</p>",
    _links: {
      self: { href: "https://api.tvmaze.com/episodes/40290" },
      show: { href: "https://api.tvmaze.com/shows/429" },
    },
  },
  {
    id: 40308,
    url: "https://www.tvmaze.com/episodes/40308/farscape-2x01-mind-the-baby",
    name: "Mind the Baby",
    season: 2,
    number: 1,
    type: "regular",
    airdate: "2000-03-17",
    airtime: "20:00",
    airstamp: "2000-03-18T01:00:00+00:00",
    runtime: 60,
    rating: { average: 7.3 },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_landscape/199/499220.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/199/499220.jpg",
    },
    summary:
      "<p>Crichton, Aeryn and D'Argo are stranded in an asteroid field while Scorpius searches for them. Their safety depends on Crais, who is nearby in <i>Talyn</i>. Aeryn teaches Crais how to control the young Leviathan - the only thing she can offer in return for the lives of her friends. When <i>Moya</i> returns to the asteroid field to look for her offspring, and Crichton decides to remove Crais from control of <i>Talyn</i>, Scorpius finally sees his chance to strike.</p>",
    _links: {
      self: { href: "https://api.tvmaze.com/episodes/40308" },
      show: { href: "https://api.tvmaze.com/shows/429" },
    },
  },
  {
    id: 40309,
    url: "https://www.tvmaze.com/episodes/40309/farscape-2x02-vitas-mortis",
    name: "Vitas Mortis",
    season: 2,
    number: 2,
    type: "regular",
    airdate: "2000-03-24",
    airtime: "20:00",
    airstamp: "2000-03-25T01:00:00+00:00",
    runtime: 60,
    rating: { average: 6.3 },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_landscape/199/499221.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/199/499221.jpg",
    },
    summary:
      "<p>D'Argo takes part in a sacred ritual that helps an old Luxan, an Orican, to survive. During the ritual the Orican draws energy from who she thinks is D'Argo but is actually <i>Moya</i>. Consequently <i>Moya</i> starts to age rapidly.</p>",
    _links: {
      self: { href: "https://api.tvmaze.com/episodes/40309" },
      show: { href: "https://api.tvmaze.com/shows/429" },
    },
  },
  {
    id: 40330,
    url: "https://www.tvmaze.com/episodes/40330/farscape-3x01-season-of-death",
    name: "Season of Death",
    season: 3,
    number: 1,
    type: "regular",
    airdate: "2001-03-16",
    airtime: "20:00",
    airstamp: "2001-03-17T01:00:00+00:00",
    runtime: 60,
    rating: { average: 8 },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_landscape/199/499242.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/199/499242.jpg",
    },
    summary:
      "<p>The Diagnosan's assistant, Grunchlk, sets a Scarran loose. Scorpius uses a device to control Grunchlk and plots to escape from the ice planet with John's neural chip.</p>",
    _links: {
      self: { href: "https://api.tvmaze.com/episodes/40330" },
      show: { href: "https://api.tvmaze.com/shows/429" },
    },
  },
  {
    id: 40331,
    url: "https://www.tvmaze.com/episodes/40331/farscape-3x02-suns-and-lovers",
    name: "Suns and Lovers",
    season: 3,
    number: 2,
    type: "regular",
    airdate: "2001-03-23",
    airtime: "20:00",
    airstamp: "2001-03-24T01:00:00+00:00",
    runtime: 60,
    rating: { average: 6.4 },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_landscape/199/499243.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/199/499243.jpg",
    },
    summary:
      "<p><i>Moya</i> docks at a commerce station so the crew can spend some of the money they acquired from the depository. There are complications, however, when a storm strikes the station.</p>",
    _links: {
      self: { href: "https://api.tvmaze.com/episodes/40331" },
      show: { href: "https://api.tvmaze.com/shows/429" },
    },
  },
  {
    id: 40352,
    url: "https://www.tvmaze.com/episodes/40352/farscape-4x01-crichton-kicks",
    name: "Crichton Kicks",
    season: 4,
    number: 1,
    type: "regular",
    airdate: "2002-06-07",
    airtime: "20:00",
    airstamp: "2002-06-08T00:00:00+00:00",
    runtime: 60,
    rating: { average: 7.3 },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_landscape/199/499264.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/199/499264.jpg",
    },
    summary:
      "<p>Crichton, who is now aboard a dying Leviathan named <i>Elack</i>, works on his theories of wormhole physics. But when a female alien named Sikozu lands on the ship, she is followed by a squad of Grudek mercenaries who want to harvest the Leviathan's neural cluster tissue. Crichton struggles to save his new home but gets some welcome help when two old friends rejoin him.</p>",
    _links: {
      self: { href: "https://api.tvmaze.com/episodes/40352" },
      show: { href: "https://api.tvmaze.com/shows/429" },
    },
  },
  {
    id: 40353,
    url: "https://www.tvmaze.com/episodes/40353/farscape-4x02-what-was-lost-part-i-sacrifice",
    name: "What Was Lost Part I: Sacrifice",
    season: 4,
    number: 2,
    type: "regular",
    airdate: "2002-06-14",
    airtime: "20:00",
    airstamp: "2002-06-15T00:00:00+00:00",
    runtime: 60,
    rating: { average: 7.5 },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_landscape/199/499265.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/199/499265.jpg",
    },
    summary:
      "<p><i>Elack</i> arrives at a planet and Crichton, Chiana and Rygel are reunited with D'Argo and Jool who are at an archaeological site run by Jool's people, the Interions. The purpose of the dig is to find a missing probe which might reverse the dangerous atmosphere of the planet. But things take a turn for the worse when Peacekeepers led by Grayza land on the planet.</p>",
    _links: {
      self: { href: "https://api.tvmaze.com/episodes/40353" },
      show: { href: "https://api.tvmaze.com/shows/429" },
    },
  },
  {
    id: 40354,
    url: "https://www.tvmaze.com/episodes/40354/farscape-4x03-what-was-lost-part-ii-resurrection",
    name: "What Was Lost Part II: Resurrection",
    season: 4,
    number: 3,
    type: "regular",
    airdate: "2002-06-21",
    airtime: "20:00",
    airstamp: "2002-06-22T00:00:00+00:00",
    runtime: 60,
    rating: { average: 7.1 },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_landscape/199/499266.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/199/499266.jpg",
    },
    summary:
      "<p>When D'Argo and Sikozu come up with a plan to crash <i>Elack</i> (the dying Leviathan) into the Peacekeeper pursuit craft, Crichton is forced to get closer with Grayza to ensure the success of the plan. But when the plan goes wrong Crichton and the rest of the crew are forced to go looking for the third probe to end the magnetic summer forever.</p>",
    _links: {
      self: { href: "https://api.tvmaze.com/episodes/40354" },
      show: { href: "https://api.tvmaze.com/shows/429" },
    },
  },
];

export const episodesGroupedBySeason: EpisodesGroupedBySeason = {
  "1": [
    {
      id: 40286,
      url: "https://www.tvmaze.com/episodes/40286/farscape-1x01-premiere",
      name: "Premiere",
      season: 1,
      number: 1,
      type: "regular",
      airdate: "1999-03-19",
      airtime: "20:00",
      airstamp: "1999-03-20T01:00:00+00:00",
      runtime: 60,
      rating: {
        average: 6.7,
      },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_landscape/199/499198.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/199/499198.jpg",
      },
      summary:
        "<p>Astronaut John Crichton attempts to use the Earth's atmosphere to propel his module <i>Farscape 1</i> at high speeds but he is hit by a radiation wave and sucked through a wormhole into a distant part of the universe and straight into the middle of a space battle. After almost colliding with another ship, which explodes shortly afterwards, he is brought aboard a ship full of alien prisoners attempting to escape custody. After being partnered with a captured Peacekeeper soldier, Crichton is drawn into the prisoners' daring plan to escape the clutches of the Peacekeeper forces and their vengefully obsessed military commander.</p>",
      _links: {
        self: {
          href: "https://api.tvmaze.com/episodes/40286",
        },
        show: {
          href: "https://api.tvmaze.com/shows/429",
        },
      },
    },
    {
      id: 40290,
      url: "https://www.tvmaze.com/episodes/40290/farscape-1x02-back-and-back-and-back-to-the-future",
      name: "Back and Back and Back to the Future",
      season: 1,
      number: 2,
      type: "regular",
      airdate: "1999-03-26",
      airtime: "20:00",
      airstamp: "1999-03-27T01:00:00+00:00",
      runtime: 60,
      rating: {
        average: 7.2,
      },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_landscape/448/1121513.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/448/1121513.jpg",
      },
      summary:
        "<p>The crew comes across a ship that is molecularly de-stabilizing. D'Argo makes everyone bring the ship's escape pod aboard when he discovers that the ship's passengers are Ilanics -- long-time allies of the Luxans. Aboard the escape pod, Crichton gets a shock and starts experiencing strange visions of the future, first of himself and one of the Ilanics, then of <i>Moya's</i> destruction.</p>",
      _links: {
        self: {
          href: "https://api.tvmaze.com/episodes/40290",
        },
        show: {
          href: "https://api.tvmaze.com/shows/429",
        },
      },
    },
  ],
  "2": [
    {
      id: 40308,
      url: "https://www.tvmaze.com/episodes/40308/farscape-2x01-mind-the-baby",
      name: "Mind the Baby",
      season: 2,
      number: 1,
      type: "regular",
      airdate: "2000-03-17",
      airtime: "20:00",
      airstamp: "2000-03-18T01:00:00+00:00",
      runtime: 60,
      rating: {
        average: 7.3,
      },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_landscape/199/499220.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/199/499220.jpg",
      },
      summary:
        "<p>Crichton, Aeryn and D'Argo are stranded in an asteroid field while Scorpius searches for them. Their safety depends on Crais, who is nearby in <i>Talyn</i>. Aeryn teaches Crais how to control the young Leviathan - the only thing she can offer in return for the lives of her friends. When <i>Moya</i> returns to the asteroid field to look for her offspring, and Crichton decides to remove Crais from control of <i>Talyn</i>, Scorpius finally sees his chance to strike.</p>",
      _links: {
        self: {
          href: "https://api.tvmaze.com/episodes/40308",
        },
        show: {
          href: "https://api.tvmaze.com/shows/429",
        },
      },
    },
    {
      id: 40309,
      url: "https://www.tvmaze.com/episodes/40309/farscape-2x02-vitas-mortis",
      name: "Vitas Mortis",
      season: 2,
      number: 2,
      type: "regular",
      airdate: "2000-03-24",
      airtime: "20:00",
      airstamp: "2000-03-25T01:00:00+00:00",
      runtime: 60,
      rating: {
        average: 6.3,
      },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_landscape/199/499221.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/199/499221.jpg",
      },
      summary:
        "<p>D'Argo takes part in a sacred ritual that helps an old Luxan, an Orican, to survive. During the ritual the Orican draws energy from who she thinks is D'Argo but is actually <i>Moya</i>. Consequently <i>Moya</i> starts to age rapidly.</p>",
      _links: {
        self: {
          href: "https://api.tvmaze.com/episodes/40309",
        },
        show: {
          href: "https://api.tvmaze.com/shows/429",
        },
      },
    },
  ],
  "3": [
    {
      id: 40330,
      url: "https://www.tvmaze.com/episodes/40330/farscape-3x01-season-of-death",
      name: "Season of Death",
      season: 3,
      number: 1,
      type: "regular",
      airdate: "2001-03-16",
      airtime: "20:00",
      airstamp: "2001-03-17T01:00:00+00:00",
      runtime: 60,
      rating: {
        average: 8,
      },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_landscape/199/499242.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/199/499242.jpg",
      },
      summary:
        "<p>The Diagnosan's assistant, Grunchlk, sets a Scarran loose. Scorpius uses a device to control Grunchlk and plots to escape from the ice planet with John's neural chip.</p>",
      _links: {
        self: {
          href: "https://api.tvmaze.com/episodes/40330",
        },
        show: {
          href: "https://api.tvmaze.com/shows/429",
        },
      },
    },
    {
      id: 40331,
      url: "https://www.tvmaze.com/episodes/40331/farscape-3x02-suns-and-lovers",
      name: "Suns and Lovers",
      season: 3,
      number: 2,
      type: "regular",
      airdate: "2001-03-23",
      airtime: "20:00",
      airstamp: "2001-03-24T01:00:00+00:00",
      runtime: 60,
      rating: {
        average: 6.4,
      },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_landscape/199/499243.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/199/499243.jpg",
      },
      summary:
        "<p><i>Moya</i> docks at a commerce station so the crew can spend some of the money they acquired from the depository. There are complications, however, when a storm strikes the station.</p>",
      _links: {
        self: {
          href: "https://api.tvmaze.com/episodes/40331",
        },
        show: {
          href: "https://api.tvmaze.com/shows/429",
        },
      },
    },
  ],
  "4": [
    {
      id: 40352,
      url: "https://www.tvmaze.com/episodes/40352/farscape-4x01-crichton-kicks",
      name: "Crichton Kicks",
      season: 4,
      number: 1,
      type: "regular",
      airdate: "2002-06-07",
      airtime: "20:00",
      airstamp: "2002-06-08T00:00:00+00:00",
      runtime: 60,
      rating: {
        average: 7.3,
      },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_landscape/199/499264.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/199/499264.jpg",
      },
      summary:
        "<p>Crichton, who is now aboard a dying Leviathan named <i>Elack</i>, works on his theories of wormhole physics. But when a female alien named Sikozu lands on the ship, she is followed by a squad of Grudek mercenaries who want to harvest the Leviathan's neural cluster tissue. Crichton struggles to save his new home but gets some welcome help when two old friends rejoin him.</p>",
      _links: {
        self: {
          href: "https://api.tvmaze.com/episodes/40352",
        },
        show: {
          href: "https://api.tvmaze.com/shows/429",
        },
      },
    },
    {
      id: 40353,
      url: "https://www.tvmaze.com/episodes/40353/farscape-4x02-what-was-lost-part-i-sacrifice",
      name: "What Was Lost Part I: Sacrifice",
      season: 4,
      number: 2,
      type: "regular",
      airdate: "2002-06-14",
      airtime: "20:00",
      airstamp: "2002-06-15T00:00:00+00:00",
      runtime: 60,
      rating: {
        average: 7.5,
      },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_landscape/199/499265.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/199/499265.jpg",
      },
      summary:
        "<p><i>Elack</i> arrives at a planet and Crichton, Chiana and Rygel are reunited with D'Argo and Jool who are at an archaeological site run by Jool's people, the Interions. The purpose of the dig is to find a missing probe which might reverse the dangerous atmosphere of the planet. But things take a turn for the worse when Peacekeepers led by Grayza land on the planet.</p>",
      _links: {
        self: {
          href: "https://api.tvmaze.com/episodes/40353",
        },
        show: {
          href: "https://api.tvmaze.com/shows/429",
        },
      },
    },
    {
      id: 40354,
      url: "https://www.tvmaze.com/episodes/40354/farscape-4x03-what-was-lost-part-ii-resurrection",
      name: "What Was Lost Part II: Resurrection",
      season: 4,
      number: 3,
      type: "regular",
      airdate: "2002-06-21",
      airtime: "20:00",
      airstamp: "2002-06-22T00:00:00+00:00",
      runtime: 60,
      rating: {
        average: 7.1,
      },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_landscape/199/499266.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/199/499266.jpg",
      },
      summary:
        "<p>When D'Argo and Sikozu come up with a plan to crash <i>Elack</i> (the dying Leviathan) into the Peacekeeper pursuit craft, Crichton is forced to get closer with Grayza to ensure the success of the plan. But when the plan goes wrong Crichton and the rest of the crew are forced to go looking for the third probe to end the magnetic summer forever.</p>",
      _links: {
        self: {
          href: "https://api.tvmaze.com/episodes/40354",
        },
        show: {
          href: "https://api.tvmaze.com/shows/429",
        },
      },
    },
  ],
};

export const ungroupedShowsByGenre: Show[] = [
  {
    id: 139,
    url: "https://www.tvmaze.com/shows/139/girls",
    name: "Girls",
    type: "Scripted",
    language: "English",
    genres: ["Drama", "Romance"],
    status: "Ended",
    runtime: 30,
    averageRuntime: 30,
    premiered: "2012-04-15",
    ended: "2017-04-16",
    officialSite: "http://www.hbo.com/girls",
    schedule: {
      time: "22:00",
      days: ["Sunday"],
    },
    rating: {
      average: 6.5,
    },
    weight: 94,
    network: {
      id: 8,
      name: "HBO",
      country: {
        name: "United States",
        code: "US",
        timezone: "America/New_York",
      },
      officialSite: "https://www.hbo.com/",
    },
    webChannel: null,
    dvdCountry: null,
    externals: {
      tvrage: 30124,
      thetvdb: 220411,
      imdb: "tt1723816",
    },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_portrait/31/78286.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/31/78286.jpg",
    },
    summary:
      "<p>This Emmy winning series is a comic look at the assorted humiliations and rare triumphs of a group of girls in their 20s.</p>",
    updated: 1704794122,
    _links: {
      self: {
        href: "https://api.tvmaze.com/shows/139",
      },
      previousepisode: {
        href: "https://api.tvmaze.com/episodes/1079686",
      },
    },
  },
  {
    id: 41734,
    url: "https://www.tvmaze.com/shows/41734/girls",
    name: "GIRLS",
    type: "Scripted",
    language: "Mongolian",
    genres: ["Comedy"],
    status: "Ended",
    runtime: 41,
    averageRuntime: null,
    premiered: null,
    ended: null,
    officialSite: null,
    schedule: {
      time: "",
      days: ["Thursday"],
    },
    rating: {
      average: null,
    },
    weight: 62,
    network: {
      id: 1672,
      name: "UBS",
      country: {
        name: "Mongolia",
        code: "MN",
        timezone: "Asia/Ulaanbaatar",
      },
      officialSite: null,
    },
    webChannel: null,
    dvdCountry: null,
    externals: {
      tvrage: null,
      thetvdb: null,
      imdb: "tt8709752",
    },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_portrait/191/478539.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/191/478539.jpg",
    },
    summary: null,
    updated: 1632080861,
    _links: {
      self: {
        href: "https://api.tvmaze.com/shows/41734",
      },
    },
  },
  {
    id: 525,
    url: "https://www.tvmaze.com/shows/525/gilmore-girls",
    name: "Gilmore Girls",
    type: "Scripted",
    language: "English",
    genres: ["Drama", "Comedy", "Romance"],
    status: "Ended",
    runtime: 60,
    averageRuntime: 60,
    premiered: "2000-10-05",
    ended: "2007-05-15",
    officialSite: null,
    schedule: {
      time: "21:00",
      days: ["Tuesday"],
    },
    rating: {
      average: 8.2,
    },
    weight: 96,
    network: {
      id: 5,
      name: "CW",
      country: {
        name: "United States",
        code: "US",
        timezone: "America/New_York",
      },
      officialSite: "https://www.cwtv.com/",
    },
    webChannel: null,
    dvdCountry: null,
    externals: {
      tvrage: 3683,
      thetvdb: 76568,
      imdb: "tt0238784",
    },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_portrait/4/11308.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/4/11308.jpg",
    },
    summary:
      "<p><b>Gilmore Girls</b> is a drama centering around the relationship between a thirtysomething single mother and her teen daughter living in Stars Hollow, Connecticut.</p>",
    updated: 1704794301,
    _links: {
      self: {
        href: "https://api.tvmaze.com/shows/525",
      },
      previousepisode: {
        href: "https://api.tvmaze.com/episodes/47639",
      },
    },
  },
  {
    id: 23542,
    url: "https://www.tvmaze.com/shows/23542/good-girls",
    name: "Good Girls",
    type: "Scripted",
    language: "English",
    genres: ["Drama", "Comedy", "Crime"],
    status: "Ended",
    runtime: 60,
    averageRuntime: 60,
    premiered: "2018-02-26",
    ended: "2021-07-22",
    officialSite: "https://www.nbc.com/good-girls",
    schedule: {
      time: "21:00",
      days: ["Thursday"],
    },
    rating: {
      average: 7.2,
    },
    weight: 95,
    network: {
      id: 1,
      name: "NBC",
      country: {
        name: "United States",
        code: "US",
        timezone: "America/New_York",
      },
      officialSite: "https://www.nbc.com/",
    },
    webChannel: null,
    dvdCountry: null,
    externals: {
      tvrage: null,
      thetvdb: 328577,
      imdb: "tt6474378",
    },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_portrait/297/744253.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/297/744253.jpg",
    },
    summary:
      '<p><b>Good Girls</b> follows three "good girl" suburban wives and mothers who suddenly find themselves in desperate circumstances and decide to stop playing it safe, and risk everything to take their power back.</p>',
    updated: 1705421176,
    _links: {
      self: {
        href: "https://api.tvmaze.com/shows/23542",
      },
      previousepisode: {
        href: "https://api.tvmaze.com/episodes/2108575",
      },
    },
  },
  {
    id: 33320,
    url: "https://www.tvmaze.com/shows/33320/derry-girls",
    name: "Derry Girls",
    type: "Scripted",
    language: "English",
    genres: ["Comedy"],
    status: "Ended",
    runtime: null,
    averageRuntime: 33,
    premiered: "2018-01-04",
    ended: "2022-05-18",
    officialSite: "http://www.channel4.com/programmes/derry-girls",
    schedule: {
      time: "",
      days: [],
    },
    rating: {
      average: 7.8,
    },
    weight: 87,
    network: {
      id: 45,
      name: "Channel 4",
      country: {
        name: "United Kingdom",
        code: "GB",
        timezone: "Europe/London",
      },
      officialSite: "https://www.channel4.com/",
    },
    webChannel: null,
    dvdCountry: null,
    externals: {
      tvrage: null,
      thetvdb: 338903,
      imdb: "tt7120662",
    },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_portrait/402/1007479.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/402/1007479.jpg",
    },
    summary:
      "<p>16-year-old Erin Quinn lives with her uncompromising mother, her long-suffering father and the fearsome ‘Granda Joe', a man whose love for his daughters and granddaughters is surpassed only by his contempt for his son-in-law.</p><p>It's the early 90s, and Erin is used to seeing her country on the nightly news and speaking in acronyms (The IRA, The UDA, The RUC). This is a time of armed police in armoured Land Rovers and British Army check points. But it's also the time of Murder She Wrote, The Cranberries, MJ and Lisa Marie, Doc Martens, bomber jackets, The X Files, Nirvana and Wayne's World. And while The Troubles may hang over her home town, Erin has troubles of her own</p>",
    updated: 1682169909,
    _links: {
      self: {
        href: "https://api.tvmaze.com/shows/33320",
      },
      previousepisode: {
        href: "https://api.tvmaze.com/episodes/2323336",
      },
    },
  },
  {
    id: 42986,
    url: "https://www.tvmaze.com/shows/42986/paper-girls",
    name: "Paper Girls",
    type: "Scripted",
    language: "English",
    genres: ["Drama", "Science-Fiction"],
    status: "Ended",
    runtime: null,
    averageRuntime: 44,
    premiered: "2022-07-29",
    ended: "2022-07-29",
    officialSite: "https://www.primevideo.com/detail/0SXAIJ5V3UWT5NQ8O0DV44N2F4/",
    schedule: {
      time: "",
      days: [],
    },
    rating: {
      average: 6.7,
    },
    weight: 83,
    network: null,
    webChannel: {
      id: 3,
      name: "Prime Video",
      country: null,
      officialSite: "https://www.primevideo.com",
    },
    dvdCountry: null,
    externals: {
      tvrage: null,
      thetvdb: 368187,
      imdb: "tt10623646",
    },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_portrait/417/1043587.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/417/1043587.jpg",
    },
    summary:
      "<p><b>Paper Girls </b>follows four young girls who, while out delivering papers on the morning after Halloween in 1988, become unwittingly caught in a conflict between warring factions of time-travelers, sending them on an adventure through time that will save the world. As they travel between our present, the past, and the future — they encounter future versions of themselves and now must choose to embrace or reject their fate. An emotional adventure in which the girls and the women they eventually become are tough, their friendships are authentic, and their journey through time is epic.</p>",
    updated: 1704809643,
    _links: {
      self: {
        href: "https://api.tvmaze.com/shows/42986",
      },
      previousepisode: {
        href: "https://api.tvmaze.com/episodes/2342540",
      },
    },
  },
  {
    id: 59431,
    url: "https://www.tvmaze.com/shows/59431/surfside-girls",
    name: "Surfside Girls",
    type: "Scripted",
    language: "English",
    genres: ["Drama", "Children", "Family"],
    status: "To Be Determined",
    runtime: null,
    averageRuntime: 24,
    premiered: "2022-08-19",
    ended: null,
    officialSite: "https://tv.apple.com/show/surfside-girls/umc.cmc.4371g2xacdr0wfs071dm3q30x",
    schedule: {
      time: "",
      days: [],
    },
    rating: {
      average: null,
    },
    weight: 82,
    network: null,
    webChannel: {
      id: 310,
      name: "Apple TV+",
      country: null,
      officialSite: "https://tv.apple.com/",
    },
    dvdCountry: null,
    externals: {
      tvrage: null,
      thetvdb: 414549,
      imdb: "tt16390162",
    },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_portrait/418/1047231.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/418/1047231.jpg",
    },
    summary:
      "<p>Sam and Jade are psyched to spend their summer riding the waves and catching the rays. That is until they meet a ghost. The girls dive head-first into a mystery about a pirate ship and the cursed treasure that allegedly lies beneath Surfside's beloved Danger Point bluff. After meeting a pirate ghost named Remi, Sam wants to help him break the curse while Jade is determined to find a scientific explanation for the existence of ghosts. To solve the mystery, Sam and Jade will need to combine their very different approaches of logic and imagination. Together, they are determined to connect the clues, solve the mystery and save Surfside... and maybe they'll help a couple of pirate ghosts along the way.</p>",
    updated: 1676106229,
    _links: {
      self: {
        href: "https://api.tvmaze.com/shows/59431",
      },
      previousepisode: {
        href: "https://api.tvmaze.com/episodes/2376047",
      },
    },
  },
  {
    id: 67594,
    url: "https://www.tvmaze.com/shows/67594/dope-girls",
    name: "Dope Girls",
    type: "Scripted",
    language: "English",
    genres: ["Drama", "Crime", "History"],
    status: "In Development",
    runtime: 60,
    averageRuntime: null,
    premiered: null,
    ended: null,
    officialSite: null,
    schedule: {
      time: "",
      days: [],
    },
    rating: {
      average: null,
    },
    weight: 79,
    network: {
      id: 12,
      name: "BBC One",
      country: {
        name: "United Kingdom",
        code: "GB",
        timezone: "Europe/London",
      },
      officialSite: "https://www.bbc.co.uk/bbcone",
    },
    webChannel: null,
    dvdCountry: null,
    externals: {
      tvrage: null,
      thetvdb: null,
      imdb: "tt27191732",
    },
    image: null,
    summary:
      "<p><b>Dope Girls</b> is inspired by a forgotten time in history when, after the losses of World War One, the streets of Soho were home to female gangs running the clubs, drugs and moonshine.</p>",
    updated: 1700083548,
    _links: {
      self: {
        href: "https://api.tvmaze.com/shows/67594",
      },
    },
  },
  {
    id: 5451,
    url: "https://www.tvmaze.com/shows/5451/golden-girls",
    name: "Golden Girls",
    type: "Scripted",
    language: "Dutch",
    genres: ["Comedy", "Family", "Romance"],
    status: "Ended",
    runtime: 30,
    averageRuntime: 30,
    premiered: "2012-08-25",
    ended: "2012-11-03",
    officialSite: null,
    schedule: {
      time: "20:00",
      days: ["Saturday"],
    },
    rating: {
      average: null,
    },
    weight: 76,
    network: {
      id: 112,
      name: "RTL4",
      country: {
        name: "Netherlands",
        code: "NL",
        timezone: "Europe/Amsterdam",
      },
      officialSite: null,
    },
    webChannel: null,
    dvdCountry: null,
    externals: {
      tvrage: null,
      thetvdb: 262042,
      imdb: "tt2359096",
    },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_portrait/22/55709.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/22/55709.jpg",
    },
    summary:
      "<p>Meet Barbara, Els, Toos &amp; Milly... Together they form the perfect circle of friends and live in their home in Scheveningen. The scripts are based on original American screenplays, but have been rewritten into Dutch and the year 2012.</p>",
    updated: 1624285127,
    _links: {
      self: {
        href: "https://api.tvmaze.com/shows/5451",
      },
      previousepisode: {
        href: "https://api.tvmaze.com/episodes/2117447",
      },
    },
  },
  {
    id: 1308,
    url: "https://www.tvmaze.com/shows/1308/bad-girls",
    name: "Bad Girls",
    type: "Scripted",
    language: "English",
    genres: ["Drama", "Crime", "Romance"],
    status: "Ended",
    runtime: 60,
    averageRuntime: 61,
    premiered: "1999-06-01",
    ended: "2006-12-18",
    officialSite: null,
    schedule: {
      time: "21:00",
      days: ["Thursday"],
    },
    rating: {
      average: 7.8,
    },
    weight: 77,
    network: {
      id: 35,
      name: "ITV1",
      country: {
        name: "United Kingdom",
        code: "GB",
        timezone: "Europe/London",
      },
      officialSite: "https://www.itv.com/",
    },
    webChannel: null,
    dvdCountry: null,
    externals: {
      tvrage: 2701,
      thetvdb: 75328,
      imdb: "tt0203248",
    },
    image: {
      medium: "https://static.tvmaze.com/uploads/images/medium_portrait/7/18492.jpg",
      original: "https://static.tvmaze.com/uploads/images/original_untouched/7/18492.jpg",
    },
    summary:
      "<p>Step inside HMP Larkhall and meet the women of G-Wing, who've committed various offences that range from shoplifting to murder. <b>Bad Girls</b> shows what life is like for these women in the 'inside world' and also shows the real-life problems (and maybe behaviour!) of the officers who watch them!</p>",
    updated: 1704793701,
    _links: {
      self: {
        href: "https://api.tvmaze.com/shows/1308",
      },
      previousepisode: {
        href: "https://api.tvmaze.com/episodes/111010",
      },
    },
  },
];

export const groupedShowsByGenre: GroupedShowsByGenre = {
  children: [
    {
      id: 59431,
      url: "https://www.tvmaze.com/shows/59431/surfside-girls",
      name: "Surfside Girls",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Children", "Family"],
      status: "To Be Determined",
      runtime: null,
      averageRuntime: 24,
      premiered: "2022-08-19",
      ended: null,
      officialSite: "https://tv.apple.com/show/surfside-girls/umc.cmc.4371g2xacdr0wfs071dm3q30x",
      schedule: { time: "", days: [] },
      rating: { average: null },
      weight: 82,
      network: null,
      webChannel: {
        id: 310,
        name: "Apple TV+",
        country: null,
        officialSite: "https://tv.apple.com/",
      },
      dvdCountry: null,
      externals: { tvrage: null, thetvdb: 414549, imdb: "tt16390162" },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_portrait/418/1047231.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/418/1047231.jpg",
      },
      summary:
        "<p>Sam and Jade are psyched to spend their summer riding the waves and catching the rays. That is until they meet a ghost. The girls dive head-first into a mystery about a pirate ship and the cursed treasure that allegedly lies beneath Surfside's beloved Danger Point bluff. After meeting a pirate ghost named Remi, Sam wants to help him break the curse while Jade is determined to find a scientific explanation for the existence of ghosts. To solve the mystery, Sam and Jade will need to combine their very different approaches of logic and imagination. Together, they are determined to connect the clues, solve the mystery and save Surfside... and maybe they'll help a couple of pirate ghosts along the way.</p>",
      updated: 1676106229,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/59431" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/2376047" },
      },
    },
  ],
  comedy: [
    {
      id: 41734,
      url: "https://www.tvmaze.com/shows/41734/girls",
      name: "GIRLS",
      type: "Scripted",
      language: "Mongolian",
      genres: ["Comedy"],
      status: "Ended",
      runtime: 41,
      averageRuntime: null,
      premiered: null,
      ended: null,
      officialSite: null,
      schedule: { time: "", days: ["Thursday"] },
      rating: { average: null },
      weight: 62,
      network: {
        id: 1672,
        name: "UBS",
        country: { name: "Mongolia", code: "MN", timezone: "Asia/Ulaanbaatar" },
        officialSite: null,
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: null, thetvdb: null, imdb: "tt8709752" },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_portrait/191/478539.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/191/478539.jpg",
      },
      summary: null,
      updated: 1632080861,
      _links: { self: { href: "https://api.tvmaze.com/shows/41734" } },
    },
    {
      id: 525,
      url: "https://www.tvmaze.com/shows/525/gilmore-girls",
      name: "Gilmore Girls",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Comedy", "Romance"],
      status: "Ended",
      runtime: 60,
      averageRuntime: 60,
      premiered: "2000-10-05",
      ended: "2007-05-15",
      officialSite: null,
      schedule: { time: "21:00", days: ["Tuesday"] },
      rating: { average: 8.2 },
      weight: 96,
      network: {
        id: 5,
        name: "CW",
        country: { name: "United States", code: "US", timezone: "America/New_York" },
        officialSite: "https://www.cwtv.com/",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 3683, thetvdb: 76568, imdb: "tt0238784" },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_portrait/4/11308.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/4/11308.jpg",
      },
      summary:
        "<p><b>Gilmore Girls</b> is a drama centering around the relationship between a thirtysomething single mother and her teen daughter living in Stars Hollow, Connecticut.</p>",
      updated: 1704794301,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/525" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/47639" },
      },
    },
    {
      id: 23542,
      url: "https://www.tvmaze.com/shows/23542/good-girls",
      name: "Good Girls",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Comedy", "Crime"],
      status: "Ended",
      runtime: 60,
      averageRuntime: 60,
      premiered: "2018-02-26",
      ended: "2021-07-22",
      officialSite: "https://www.nbc.com/good-girls",
      schedule: { time: "21:00", days: ["Thursday"] },
      rating: { average: 7.2 },
      weight: 95,
      network: {
        id: 1,
        name: "NBC",
        country: { name: "United States", code: "US", timezone: "America/New_York" },
        officialSite: "https://www.nbc.com/",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: null, thetvdb: 328577, imdb: "tt6474378" },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_portrait/297/744253.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/297/744253.jpg",
      },
      summary:
        '<p><b>Good Girls</b> follows three "good girl" suburban wives and mothers who suddenly find themselves in desperate circumstances and decide to stop playing it safe, and risk everything to take their power back.</p>',
      updated: 1705421176,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/23542" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/2108575" },
      },
    },
    {
      id: 33320,
      url: "https://www.tvmaze.com/shows/33320/derry-girls",
      name: "Derry Girls",
      type: "Scripted",
      language: "English",
      genres: ["Comedy"],
      status: "Ended",
      runtime: null,
      averageRuntime: 33,
      premiered: "2018-01-04",
      ended: "2022-05-18",
      officialSite: "http://www.channel4.com/programmes/derry-girls",
      schedule: { time: "", days: [] },
      rating: { average: 7.8 },
      weight: 87,
      network: {
        id: 45,
        name: "Channel 4",
        country: { name: "United Kingdom", code: "GB", timezone: "Europe/London" },
        officialSite: "https://www.channel4.com/",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: null, thetvdb: 338903, imdb: "tt7120662" },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_portrait/402/1007479.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/402/1007479.jpg",
      },
      summary:
        "<p>16-year-old Erin Quinn lives with her uncompromising mother, her long-suffering father and the fearsome ‘Granda Joe', a man whose love for his daughters and granddaughters is surpassed only by his contempt for his son-in-law.</p><p>It's the early 90s, and Erin is used to seeing her country on the nightly news and speaking in acronyms (The IRA, The UDA, The RUC). This is a time of armed police in armoured Land Rovers and British Army check points. But it's also the time of Murder She Wrote, The Cranberries, MJ and Lisa Marie, Doc Martens, bomber jackets, The X Files, Nirvana and Wayne's World. And while The Troubles may hang over her home town, Erin has troubles of her own</p>",
      updated: 1682169909,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/33320" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/2323336" },
      },
    },
    {
      id: 5451,
      url: "https://www.tvmaze.com/shows/5451/golden-girls",
      name: "Golden Girls",
      type: "Scripted",
      language: "Dutch",
      genres: ["Comedy", "Family", "Romance"],
      status: "Ended",
      runtime: 30,
      averageRuntime: 30,
      premiered: "2012-08-25",
      ended: "2012-11-03",
      officialSite: null,
      schedule: { time: "20:00", days: ["Saturday"] },
      rating: { average: null },
      weight: 76,
      network: {
        id: 112,
        name: "RTL4",
        country: { name: "Netherlands", code: "NL", timezone: "Europe/Amsterdam" },
        officialSite: null,
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: null, thetvdb: 262042, imdb: "tt2359096" },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_portrait/22/55709.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/22/55709.jpg",
      },
      summary:
        "<p>Meet Barbara, Els, Toos &amp; Milly... Together they form the perfect circle of friends and live in their home in Scheveningen. The scripts are based on original American screenplays, but have been rewritten into Dutch and the year 2012.</p>",
      updated: 1624285127,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/5451" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/2117447" },
      },
    },
  ],
  crime: [
    {
      id: 23542,
      url: "https://www.tvmaze.com/shows/23542/good-girls",
      name: "Good Girls",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Comedy", "Crime"],
      status: "Ended",
      runtime: 60,
      averageRuntime: 60,
      premiered: "2018-02-26",
      ended: "2021-07-22",
      officialSite: "https://www.nbc.com/good-girls",
      schedule: { time: "21:00", days: ["Thursday"] },
      rating: { average: 7.2 },
      weight: 95,
      network: {
        id: 1,
        name: "NBC",
        country: { name: "United States", code: "US", timezone: "America/New_York" },
        officialSite: "https://www.nbc.com/",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: null, thetvdb: 328577, imdb: "tt6474378" },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_portrait/297/744253.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/297/744253.jpg",
      },
      summary:
        '<p><b>Good Girls</b> follows three "good girl" suburban wives and mothers who suddenly find themselves in desperate circumstances and decide to stop playing it safe, and risk everything to take their power back.</p>',
      updated: 1705421176,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/23542" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/2108575" },
      },
    },
    {
      id: 67594,
      url: "https://www.tvmaze.com/shows/67594/dope-girls",
      name: "Dope Girls",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Crime", "History"],
      status: "In Development",
      runtime: 60,
      averageRuntime: null,
      premiered: null,
      ended: null,
      officialSite: null,
      schedule: { time: "", days: [] },
      rating: { average: null },
      weight: 79,
      network: {
        id: 12,
        name: "BBC One",
        country: { name: "United Kingdom", code: "GB", timezone: "Europe/London" },
        officialSite: "https://www.bbc.co.uk/bbcone",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: null, thetvdb: null, imdb: "tt27191732" },
      image: null,
      summary:
        "<p><b>Dope Girls</b> is inspired by a forgotten time in history when, after the losses of World War One, the streets of Soho were home to female gangs running the clubs, drugs and moonshine.</p>",
      updated: 1700083548,
      _links: { self: { href: "https://api.tvmaze.com/shows/67594" } },
    },
    {
      id: 1308,
      url: "https://www.tvmaze.com/shows/1308/bad-girls",
      name: "Bad Girls",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Crime", "Romance"],
      status: "Ended",
      runtime: 60,
      averageRuntime: 61,
      premiered: "1999-06-01",
      ended: "2006-12-18",
      officialSite: null,
      schedule: { time: "21:00", days: ["Thursday"] },
      rating: { average: 7.8 },
      weight: 77,
      network: {
        id: 35,
        name: "ITV1",
        country: { name: "United Kingdom", code: "GB", timezone: "Europe/London" },
        officialSite: "https://www.itv.com/",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 2701, thetvdb: 75328, imdb: "tt0203248" },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_portrait/7/18492.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/7/18492.jpg",
      },
      summary:
        "<p>Step inside HMP Larkhall and meet the women of G-Wing, who've committed various offences that range from shoplifting to murder. <b>Bad Girls</b> shows what life is like for these women in the 'inside world' and also shows the real-life problems (and maybe behaviour!) of the officers who watch them!</p>",
      updated: 1704793701,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/1308" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/111010" },
      },
    },
  ],
  drama: [
    {
      id: 139,
      url: "https://www.tvmaze.com/shows/139/girls",
      name: "Girls",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Romance"],
      status: "Ended",
      runtime: 30,
      averageRuntime: 30,
      premiered: "2012-04-15",
      ended: "2017-04-16",
      officialSite: "http://www.hbo.com/girls",
      schedule: { time: "22:00", days: ["Sunday"] },
      rating: { average: 6.5 },
      weight: 94,
      network: {
        id: 8,
        name: "HBO",
        country: { name: "United States", code: "US", timezone: "America/New_York" },
        officialSite: "https://www.hbo.com/",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 30124, thetvdb: 220411, imdb: "tt1723816" },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_portrait/31/78286.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/31/78286.jpg",
      },
      summary:
        "<p>This Emmy winning series is a comic look at the assorted humiliations and rare triumphs of a group of girls in their 20s.</p>",
      updated: 1704794122,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/139" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/1079686" },
      },
    },
    {
      id: 525,
      url: "https://www.tvmaze.com/shows/525/gilmore-girls",
      name: "Gilmore Girls",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Comedy", "Romance"],
      status: "Ended",
      runtime: 60,
      averageRuntime: 60,
      premiered: "2000-10-05",
      ended: "2007-05-15",
      officialSite: null,
      schedule: { time: "21:00", days: ["Tuesday"] },
      rating: { average: 8.2 },
      weight: 96,
      network: {
        id: 5,
        name: "CW",
        country: { name: "United States", code: "US", timezone: "America/New_York" },
        officialSite: "https://www.cwtv.com/",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 3683, thetvdb: 76568, imdb: "tt0238784" },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_portrait/4/11308.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/4/11308.jpg",
      },
      summary:
        "<p><b>Gilmore Girls</b> is a drama centering around the relationship between a thirtysomething single mother and her teen daughter living in Stars Hollow, Connecticut.</p>",
      updated: 1704794301,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/525" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/47639" },
      },
    },
    {
      id: 23542,
      url: "https://www.tvmaze.com/shows/23542/good-girls",
      name: "Good Girls",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Comedy", "Crime"],
      status: "Ended",
      runtime: 60,
      averageRuntime: 60,
      premiered: "2018-02-26",
      ended: "2021-07-22",
      officialSite: "https://www.nbc.com/good-girls",
      schedule: { time: "21:00", days: ["Thursday"] },
      rating: { average: 7.2 },
      weight: 95,
      network: {
        id: 1,
        name: "NBC",
        country: { name: "United States", code: "US", timezone: "America/New_York" },
        officialSite: "https://www.nbc.com/",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: null, thetvdb: 328577, imdb: "tt6474378" },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_portrait/297/744253.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/297/744253.jpg",
      },
      summary:
        '<p><b>Good Girls</b> follows three "good girl" suburban wives and mothers who suddenly find themselves in desperate circumstances and decide to stop playing it safe, and risk everything to take their power back.</p>',
      updated: 1705421176,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/23542" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/2108575" },
      },
    },
    {
      id: 42986,
      url: "https://www.tvmaze.com/shows/42986/paper-girls",
      name: "Paper Girls",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Science-Fiction"],
      status: "Ended",
      runtime: null,
      averageRuntime: 44,
      premiered: "2022-07-29",
      ended: "2022-07-29",
      officialSite: "https://www.primevideo.com/detail/0SXAIJ5V3UWT5NQ8O0DV44N2F4/",
      schedule: { time: "", days: [] },
      rating: { average: 6.7 },
      weight: 83,
      network: null,
      webChannel: {
        id: 3,
        name: "Prime Video",
        country: null,
        officialSite: "https://www.primevideo.com",
      },
      dvdCountry: null,
      externals: { tvrage: null, thetvdb: 368187, imdb: "tt10623646" },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_portrait/417/1043587.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/417/1043587.jpg",
      },
      summary:
        "<p><b>Paper Girls </b>follows four young girls who, while out delivering papers on the morning after Halloween in 1988, become unwittingly caught in a conflict between warring factions of time-travelers, sending them on an adventure through time that will save the world. As they travel between our present, the past, and the future — they encounter future versions of themselves and now must choose to embrace or reject their fate. An emotional adventure in which the girls and the women they eventually become are tough, their friendships are authentic, and their journey through time is epic.</p>",
      updated: 1704809643,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/42986" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/2342540" },
      },
    },
    {
      id: 59431,
      url: "https://www.tvmaze.com/shows/59431/surfside-girls",
      name: "Surfside Girls",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Children", "Family"],
      status: "To Be Determined",
      runtime: null,
      averageRuntime: 24,
      premiered: "2022-08-19",
      ended: null,
      officialSite: "https://tv.apple.com/show/surfside-girls/umc.cmc.4371g2xacdr0wfs071dm3q30x",
      schedule: { time: "", days: [] },
      rating: { average: null },
      weight: 82,
      network: null,
      webChannel: {
        id: 310,
        name: "Apple TV+",
        country: null,
        officialSite: "https://tv.apple.com/",
      },
      dvdCountry: null,
      externals: { tvrage: null, thetvdb: 414549, imdb: "tt16390162" },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_portrait/418/1047231.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/418/1047231.jpg",
      },
      summary:
        "<p>Sam and Jade are psyched to spend their summer riding the waves and catching the rays. That is until they meet a ghost. The girls dive head-first into a mystery about a pirate ship and the cursed treasure that allegedly lies beneath Surfside's beloved Danger Point bluff. After meeting a pirate ghost named Remi, Sam wants to help him break the curse while Jade is determined to find a scientific explanation for the existence of ghosts. To solve the mystery, Sam and Jade will need to combine their very different approaches of logic and imagination. Together, they are determined to connect the clues, solve the mystery and save Surfside... and maybe they'll help a couple of pirate ghosts along the way.</p>",
      updated: 1676106229,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/59431" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/2376047" },
      },
    },
    {
      id: 67594,
      url: "https://www.tvmaze.com/shows/67594/dope-girls",
      name: "Dope Girls",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Crime", "History"],
      status: "In Development",
      runtime: 60,
      averageRuntime: null,
      premiered: null,
      ended: null,
      officialSite: null,
      schedule: { time: "", days: [] },
      rating: { average: null },
      weight: 79,
      network: {
        id: 12,
        name: "BBC One",
        country: { name: "United Kingdom", code: "GB", timezone: "Europe/London" },
        officialSite: "https://www.bbc.co.uk/bbcone",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: null, thetvdb: null, imdb: "tt27191732" },
      image: null,
      summary:
        "<p><b>Dope Girls</b> is inspired by a forgotten time in history when, after the losses of World War One, the streets of Soho were home to female gangs running the clubs, drugs and moonshine.</p>",
      updated: 1700083548,
      _links: { self: { href: "https://api.tvmaze.com/shows/67594" } },
    },
    {
      id: 1308,
      url: "https://www.tvmaze.com/shows/1308/bad-girls",
      name: "Bad Girls",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Crime", "Romance"],
      status: "Ended",
      runtime: 60,
      averageRuntime: 61,
      premiered: "1999-06-01",
      ended: "2006-12-18",
      officialSite: null,
      schedule: { time: "21:00", days: ["Thursday"] },
      rating: { average: 7.8 },
      weight: 77,
      network: {
        id: 35,
        name: "ITV1",
        country: { name: "United Kingdom", code: "GB", timezone: "Europe/London" },
        officialSite: "https://www.itv.com/",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 2701, thetvdb: 75328, imdb: "tt0203248" },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_portrait/7/18492.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/7/18492.jpg",
      },
      summary:
        "<p>Step inside HMP Larkhall and meet the women of G-Wing, who've committed various offences that range from shoplifting to murder. <b>Bad Girls</b> shows what life is like for these women in the 'inside world' and also shows the real-life problems (and maybe behaviour!) of the officers who watch them!</p>",
      updated: 1704793701,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/1308" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/111010" },
      },
    },
  ],
  family: [
    {
      id: 59431,
      url: "https://www.tvmaze.com/shows/59431/surfside-girls",
      name: "Surfside Girls",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Children", "Family"],
      status: "To Be Determined",
      runtime: null,
      averageRuntime: 24,
      premiered: "2022-08-19",
      ended: null,
      officialSite: "https://tv.apple.com/show/surfside-girls/umc.cmc.4371g2xacdr0wfs071dm3q30x",
      schedule: { time: "", days: [] },
      rating: { average: null },
      weight: 82,
      network: null,
      webChannel: {
        id: 310,
        name: "Apple TV+",
        country: null,
        officialSite: "https://tv.apple.com/",
      },
      dvdCountry: null,
      externals: { tvrage: null, thetvdb: 414549, imdb: "tt16390162" },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_portrait/418/1047231.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/418/1047231.jpg",
      },
      summary:
        "<p>Sam and Jade are psyched to spend their summer riding the waves and catching the rays. That is until they meet a ghost. The girls dive head-first into a mystery about a pirate ship and the cursed treasure that allegedly lies beneath Surfside's beloved Danger Point bluff. After meeting a pirate ghost named Remi, Sam wants to help him break the curse while Jade is determined to find a scientific explanation for the existence of ghosts. To solve the mystery, Sam and Jade will need to combine their very different approaches of logic and imagination. Together, they are determined to connect the clues, solve the mystery and save Surfside... and maybe they'll help a couple of pirate ghosts along the way.</p>",
      updated: 1676106229,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/59431" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/2376047" },
      },
    },
    {
      id: 5451,
      url: "https://www.tvmaze.com/shows/5451/golden-girls",
      name: "Golden Girls",
      type: "Scripted",
      language: "Dutch",
      genres: ["Comedy", "Family", "Romance"],
      status: "Ended",
      runtime: 30,
      averageRuntime: 30,
      premiered: "2012-08-25",
      ended: "2012-11-03",
      officialSite: null,
      schedule: { time: "20:00", days: ["Saturday"] },
      rating: { average: null },
      weight: 76,
      network: {
        id: 112,
        name: "RTL4",
        country: { name: "Netherlands", code: "NL", timezone: "Europe/Amsterdam" },
        officialSite: null,
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: null, thetvdb: 262042, imdb: "tt2359096" },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_portrait/22/55709.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/22/55709.jpg",
      },
      summary:
        "<p>Meet Barbara, Els, Toos &amp; Milly... Together they form the perfect circle of friends and live in their home in Scheveningen. The scripts are based on original American screenplays, but have been rewritten into Dutch and the year 2012.</p>",
      updated: 1624285127,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/5451" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/2117447" },
      },
    },
  ],
  history: [
    {
      id: 67594,
      url: "https://www.tvmaze.com/shows/67594/dope-girls",
      name: "Dope Girls",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Crime", "History"],
      status: "In Development",
      runtime: 60,
      averageRuntime: null,
      premiered: null,
      ended: null,
      officialSite: null,
      schedule: { time: "", days: [] },
      rating: { average: null },
      weight: 79,
      network: {
        id: 12,
        name: "BBC One",
        country: { name: "United Kingdom", code: "GB", timezone: "Europe/London" },
        officialSite: "https://www.bbc.co.uk/bbcone",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: null, thetvdb: null, imdb: "tt27191732" },
      image: null,
      summary:
        "<p><b>Dope Girls</b> is inspired by a forgotten time in history when, after the losses of World War One, the streets of Soho were home to female gangs running the clubs, drugs and moonshine.</p>",
      updated: 1700083548,
      _links: { self: { href: "https://api.tvmaze.com/shows/67594" } },
    },
  ],
  romance: [
    {
      id: 139,
      url: "https://www.tvmaze.com/shows/139/girls",
      name: "Girls",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Romance"],
      status: "Ended",
      runtime: 30,
      averageRuntime: 30,
      premiered: "2012-04-15",
      ended: "2017-04-16",
      officialSite: "http://www.hbo.com/girls",
      schedule: { time: "22:00", days: ["Sunday"] },
      rating: { average: 6.5 },
      weight: 94,
      network: {
        id: 8,
        name: "HBO",
        country: { name: "United States", code: "US", timezone: "America/New_York" },
        officialSite: "https://www.hbo.com/",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 30124, thetvdb: 220411, imdb: "tt1723816" },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_portrait/31/78286.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/31/78286.jpg",
      },
      summary:
        "<p>This Emmy winning series is a comic look at the assorted humiliations and rare triumphs of a group of girls in their 20s.</p>",
      updated: 1704794122,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/139" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/1079686" },
      },
    },
    {
      id: 525,
      url: "https://www.tvmaze.com/shows/525/gilmore-girls",
      name: "Gilmore Girls",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Comedy", "Romance"],
      status: "Ended",
      runtime: 60,
      averageRuntime: 60,
      premiered: "2000-10-05",
      ended: "2007-05-15",
      officialSite: null,
      schedule: { time: "21:00", days: ["Tuesday"] },
      rating: { average: 8.2 },
      weight: 96,
      network: {
        id: 5,
        name: "CW",
        country: { name: "United States", code: "US", timezone: "America/New_York" },
        officialSite: "https://www.cwtv.com/",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 3683, thetvdb: 76568, imdb: "tt0238784" },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_portrait/4/11308.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/4/11308.jpg",
      },
      summary:
        "<p><b>Gilmore Girls</b> is a drama centering around the relationship between a thirtysomething single mother and her teen daughter living in Stars Hollow, Connecticut.</p>",
      updated: 1704794301,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/525" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/47639" },
      },
    },
    {
      id: 5451,
      url: "https://www.tvmaze.com/shows/5451/golden-girls",
      name: "Golden Girls",
      type: "Scripted",
      language: "Dutch",
      genres: ["Comedy", "Family", "Romance"],
      status: "Ended",
      runtime: 30,
      averageRuntime: 30,
      premiered: "2012-08-25",
      ended: "2012-11-03",
      officialSite: null,
      schedule: { time: "20:00", days: ["Saturday"] },
      rating: { average: null },
      weight: 76,
      network: {
        id: 112,
        name: "RTL4",
        country: { name: "Netherlands", code: "NL", timezone: "Europe/Amsterdam" },
        officialSite: null,
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: null, thetvdb: 262042, imdb: "tt2359096" },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_portrait/22/55709.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/22/55709.jpg",
      },
      summary:
        "<p>Meet Barbara, Els, Toos &amp; Milly... Together they form the perfect circle of friends and live in their home in Scheveningen. The scripts are based on original American screenplays, but have been rewritten into Dutch and the year 2012.</p>",
      updated: 1624285127,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/5451" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/2117447" },
      },
    },
    {
      id: 1308,
      url: "https://www.tvmaze.com/shows/1308/bad-girls",
      name: "Bad Girls",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Crime", "Romance"],
      status: "Ended",
      runtime: 60,
      averageRuntime: 61,
      premiered: "1999-06-01",
      ended: "2006-12-18",
      officialSite: null,
      schedule: { time: "21:00", days: ["Thursday"] },
      rating: { average: 7.8 },
      weight: 77,
      network: {
        id: 35,
        name: "ITV1",
        country: { name: "United Kingdom", code: "GB", timezone: "Europe/London" },
        officialSite: "https://www.itv.com/",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 2701, thetvdb: 75328, imdb: "tt0203248" },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_portrait/7/18492.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/7/18492.jpg",
      },
      summary:
        "<p>Step inside HMP Larkhall and meet the women of G-Wing, who've committed various offences that range from shoplifting to murder. <b>Bad Girls</b> shows what life is like for these women in the 'inside world' and also shows the real-life problems (and maybe behaviour!) of the officers who watch them!</p>",
      updated: 1704793701,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/1308" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/111010" },
      },
    },
  ],
  scifi: [
    {
      id: 42986,
      url: "https://www.tvmaze.com/shows/42986/paper-girls",
      name: "Paper Girls",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Science-Fiction"],
      status: "Ended",
      runtime: null,
      averageRuntime: 44,
      premiered: "2022-07-29",
      ended: "2022-07-29",
      officialSite: "https://www.primevideo.com/detail/0SXAIJ5V3UWT5NQ8O0DV44N2F4/",
      schedule: { time: "", days: [] },
      rating: { average: 6.7 },
      weight: 83,
      network: null,
      webChannel: {
        id: 3,
        name: "Prime Video",
        country: null,
        officialSite: "https://www.primevideo.com",
      },
      dvdCountry: null,
      externals: { tvrage: null, thetvdb: 368187, imdb: "tt10623646" },
      image: {
        medium: "https://static.tvmaze.com/uploads/images/medium_portrait/417/1043587.jpg",
        original: "https://static.tvmaze.com/uploads/images/original_untouched/417/1043587.jpg",
      },
      summary:
        "<p><b>Paper Girls </b>follows four young girls who, while out delivering papers on the morning after Halloween in 1988, become unwittingly caught in a conflict between warring factions of time-travelers, sending them on an adventure through time that will save the world. As they travel between our present, the past, and the future — they encounter future versions of themselves and now must choose to embrace or reject their fate. An emotional adventure in which the girls and the women they eventually become are tough, their friendships are authentic, and their journey through time is epic.</p>",
      updated: 1704809643,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/42986" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/2342540" },
      },
    },
  ],
};
